[metadata]
name = tgfclient
version = 1.1.0
summary = A client application for the instruments of the UCSC TGF group.
home_page = https://github.com/JSheare/tgfclient
author = Jacob Shearer
author_email = jacob.shearer6912@gmail.com

[options]
packages = 
	tgfclient
    tgfclient/config
    tgfclient/helpers
    tgfclient/startup
    tgfclient/validation
python_requires = >=3.12
install_requires =
    paramiko
    platformdirs
	psutil
    pydantic
    tgfsearch@git+https://github.com/JSheare/tgfsearch
    websockets

[options.entry_points]
console_scripts =
    tgfclient = tgfclient.main:main

[options.package_data]
tgfclient =
    config/tgfclient.ini
	